Issue #62: Handle empty first name of creditor
Schachigel/DKV2 pull request #63
Opened 2022-03-03 22:39 UTC by wipfl

SQL statements are changed to handle empty first name (Vorname).
Display last name (Nachname) only if the combination 'Nachname, Vorname' is NULL.

2022-04-02 19:16 UTC, Schachigel requested changes
Hallo!
Kann das denn NULL werden
,IFNULL(K.Nachname || ', ' || K.Vorname, K.Nachname) AS KreditorIn
? es bleibt doch immer das Komma in der Mitte, selbst wenn die beiden anderen leer sind - oder? Ausserdem sind die Felder immer mit leerstring initialisiert - das steht so im create table SQL

2022-04-08 20:48 UTC, wipfl commented
1. Kann das denn NULL werden? -> JA
Wenn ein Operand des || Operators NULL ist, dann ist das Ergebnis NULL. Da nützt das ',' nix.

2. Die Felder sind mit Leerstring initialisiert.
Das nützt aber nix, weil das beim Update eines Records nicht der Fall ist.
Editiere einen Kreditor und lösche den Vornamen. Schon steht in der DB ein NULL-Wert. Das wird in tabledatainserter.cpp in Zeile 183/184 abgefrühstückt:
        if( record.field(i).isNull()) {
            sql += record.field(i).name() +qsl("=NULL");
Vielleicht ist das die richtige Stelle, um da (falls der Feldtyp ein String ist) stattdessen ein Leerzeichen reinzuschreiben. 

Wilhelm

2022-04-10 06:39 UTC, Schachigel commented
> 1. Kann das denn NULL werden? -> JA
>    Wenn ein Operand des || Operators NULL ist, dann ist das Ergebnis NULL. Da nützt das ',' nix.
Ja - das ist problematisch - hab ich mir angeschaut. Das gilt dann aber auch f. Nachname etc. Vlt müssen wir dann mal alle SQLs überprüfen :(

> 2. Die Felder sind mit Leerstring initialisiert.
>    Das nützt aber nix, weil das beim Update eines Records nicht der Fall ist.
>    Editiere einen Kreditor und lösche den Vornamen. Schon steht in der DB ein NULL-Wert. Das wird in tabledatainserter.cpp in Zeile 183/184 abgefrühstückt:
>    if( record.field(i).isNull()) {
>    sql += record.field(i).name() +qsl("=NULL");
>    Vielleicht ist das die richtige Stelle, um da (falls der Feldtyp ein String ist) stattdessen ein Leerzeichen reinzuschreiben.
Ja - genau. Wir müssen noch mal schauen, ob das die einzige Stelle ist. Ich möchte eigentlich NULL nur für Index Felder in der Datenbank zulassen. Können wir auch gerne mal drüber telefonieren.

2022-04-16 18:53 UTC, Schachigel commented
Hallo! Wie per mail geschrieben habe ich mit dem commit "on update do not set fields to NULL" eine Lösung implementiert, die ohne die Veränderungen im SQL auskommt. Bitte testen !

2022-04-16 18:53 UTC, closed without merging