save contractslist as csv
Schachigel/DKV2 pull request #68
Opened 2022-04-01 19:19 UTC by vopor

if contractsViewModel ist proxy model, then take source model

2022-04-02 14:22 UTC, vopor commented
fixes #64

2022-04-02 19:10 UTC, Schachigel requested changes
Danke für den Fix. Benötigt man die if s denn? Wie ich das verstehe habe ich das übersehen als ich das proxy model eingeführt habe. Du könntest also einfach gleich das Proxy Model holen und das source model abfragen - ohne vorher das model auf QSqlTableModel zu casten. Das kann ja nie gut gehen - oder?

2022-04-03 12:18 UTC, Schachigel commented
Hallo! Ich werde die Änderung ohne die Abfragen in meinen nächsten commit übernehmen.

2022-04-03 12:18 UTC, closed without merging

2022-04-03 15:07 UTC, vopor commented
Ok, super!
Ja, die Abfrage braucht man nicht, wenn klar ist, dass das contractsTableView->model() immer ein proxyModel() ist.