Fix building process
Schachigel/DKV2 pull request #85
Opened 2022-11-17 22:22 UTC by plant-hedgerows

Hallo lieber Schachigel,

ich wohne in einem Hausprojekt in Hamburg und meine Direktkredite AG will DKV2 zur Direktkreditverwaltung nutzen.

Jedenfalls wollte ich versuchen es zu bauen und habe einige Sachen gefunden, die auf meiner Maschiene nicht funktioniert haben. 

Dann habe ich versucht alles zu reparieren. Es gibt leider ein letztes problem das qmake aufwirft (s.u.), dafür ist die build environment schlanker und funktioniert (bei mir).

Es ist das zweite mal das ich git benutze und ich bin mir nicht sicher ob ich ansatzweise etwas richtig mache :) 

Vielleicht findest du ja Zeit und Lust und Inspiration dir anzuschauen was ich da rumgerödelt habe. Ich wäre über Feedback sehr dankbar -- vielleicht kannst du ja den ein oder anderen commit in dein repo aufnehmen.

Liebe Grüße aus HH,
Lukas

hier die Ausgabe des build prozesses -- es liegt wohl an der datatables.cpp line 26.

```
Building with QTDIR: `/qt`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/app/build-dist-linux /app
Info: creating stash file /app/build-dist-linux/.qmake.stash
/usr/lib/qt5/bin/uic ../DKV2/mainwindow.ui -o ui_mainwindow.h

[...]

/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o dbtable.o ../DKV2/dbtable.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:51,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug:1,
                 from ../DKV2/pch.h:10:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h: In instantiation of 'void QVector<T>::reallocData(int, int, QArrayData::AllocationOptions) [with T = dbForeignKey; QArrayData::AllocationOptions = QFlags<QArrayData::AllocationOption>]':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:682:9:   required from 'void QVector<T>::append(const T&) [with T = dbForeignKey]'
../DKV2/dbtable.cpp:26:26:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:607:33: error: no matching function for call to 'dbForeignKey::dbForeignKey()'
  607 |                                 new (dst++) T();
      |                                 ^~~~~~~~~~~~~~~
In file included from ../DKV2/dbtable.h:4,
                 from ../DKV2/helpersql.h:6,
                 from ../DKV2/dbtable.cpp:3:
../DKV2/dbfield.h:56:5: note: candidate: 'dbForeignKey::dbForeignKey(const dbfield&, const QString&, const QString&, ODOU_Action, ODOU_Action)'
   56 |     dbForeignKey(const dbfield& local, const QString& parentTable, const QString& parentField, ODOU_Action delAction =NO_ACTION, ODOU_Action updAction =NO_ACTION)
      |     ^~~~~~~~~~~~
../DKV2/dbfield.h:56:5: note:   candidate expects 5 arguments, 0 provided
../DKV2/dbfield.h:47:5: note: candidate: 'dbForeignKey::dbForeignKey(const dbfield&, const dbfield&, ODOU_Action, ODOU_Action)'
   47 |     dbForeignKey(const dbfield& local, const dbfield& parent, ODOU_Action delAction =NO_ACTION, ODOU_Action updAction =NO_ACTION)
      |     ^~~~~~~~~~~~
../DKV2/dbfield.h:47:5: note:   candidate expects 4 arguments, 0 provided
../DKV2/dbfield.h:43:8: note: candidate: 'dbForeignKey::dbForeignKey(const dbForeignKey&)'
   43 | struct dbForeignKey
      |        ^~~~~~~~~~~~
../DKV2/dbfield.h:43:8: note:   candidate expects 1 argument, 0 provided
../DKV2/dbfield.h:43:8: note: candidate: 'dbForeignKey::dbForeignKey(dbForeignKey&&)'
../DKV2/dbfield.h:43:8: note:   candidate expects 1 argument, 0 provided

[....]

make: *** [Makefile:851: dbtable.o] Error 1
make: *** Waiting for unfinished jobs....
```

2022-11-20 07:52 UTC, Schachigel commented
Grüß Dich, Lukas. Schön, dass Du Dich bei DKV2 einbringen möchtest.
Zu Deinem Pull request habe ich Kommentare abgegeben. Du hast mehrmals
memory included, aber ich sehe keine Verwendung. Zum Dockerfile kann ich
nicht viel sagen - ich baue Linux lokal ohne Docker (in der Windows WSL)
und in der Github Action wird Docker auch nicht verwendet. Ich kann dazu
also nichts sagen. Vlt. kommentiert Frando. Aber ich würde keine Variablen
durch fest eingegebene Ordner wie /usr ersetzten. Es soll ja nicht nur bei
Dir funktionieren. Die Lösung für so etwas sollte sein, dass Du die
Variable auf Deinem System auf den richtigen Wert setzt.
Also ganz allgemein: So kann ich Deinen PR nicht verwenden. Eine Änderung
muss auf Windows in meiner WSL und auf Github laufen.
Sollen wir mal telefonieren?
Gruß
Holger

Am Do., 17. Nov. 2022 um 23:23 Uhr schrieb plant-hedgerows <
***@***.***>:

> Hallo lieber Schachigel,
>
> ich wohne in einem Hausprojekt in Hamburg und meine Direktkredite AG will
> DKV2 zur Direktkreditverwaltung nutzen.
>
> Jedenfalls wollte ich versuchen es zu bauen und habe einige Sachen
> gefunden, die auf meiner Maschiene nicht funktioniert haben.
>
> Dann habe ich versucht alles zu reparieren. Es gibt leider ein letztes
> problem das qmake aufwirft (s.u.), dafür ist die build environment
> schlanker und funktioniert (bei mir).
>
> Es ist das zweite mal das ich git benutze und ich bin mir nicht sicher ob
> ich ansatzweise etwas richtig mache :)
>
> Vielleicht findest du ja Zeit und Lust und Inspiration dir anzuschauen was
> ich da rumgerödelt habe. Ich wäre über Feedback sehr dankbar -- vielleicht
> kannst du ja den ein oder anderen commit in dein repo aufnehmen.
>
> Liebe Grüße aus HH,
> Lukas
>
> hier die Ausgabe des build prozesses -- es liegt wohl an der
> datatables.cpp line 26.
>
> Building with QTDIR: `/qt`
>
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>
>                                  Dload  Upload   Total   Spent    Left  Speed
>
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>
> /app/build-dist-linux /app
>
> Info: creating stash file /app/build-dist-linux/.qmake.stash
>
> /usr/lib/qt5/bin/uic ../DKV2/mainwindow.ui -o ui_mainwindow.h
>
>
>
> [...]
>
>
>
> /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o dbtable.o ../DKV2/dbtable.cpp
>
> In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:51,
>
>                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug:1,
>
>                  from ../DKV2/pch.h:10:
>
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h: In instantiation of 'void QVector<T>::reallocData(int, int, QArrayData::AllocationOptions) [with T = dbForeignKey; QArrayData::AllocationOptions = QFlags<QArrayData::AllocationOption>]':
>
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:682:9:   required from 'void QVector<T>::append(const T&) [with T = dbForeignKey]'
>
> ../DKV2/dbtable.cpp:26:26:   required from here
>
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:607:33: error: no matching function for call to 'dbForeignKey::dbForeignKey()'
>
>   607 |                                 new (dst++) T();
>
>       |                                 ^~~~~~~~~~~~~~~
>
> In file included from ../DKV2/dbtable.h:4,
>
>                  from ../DKV2/helpersql.h:6,
>
>                  from ../DKV2/dbtable.cpp:3:
>
> ../DKV2/dbfield.h:56:5: note: candidate: 'dbForeignKey::dbForeignKey(const dbfield&, const QString&, const QString&, ODOU_Action, ODOU_Action)'
>
>    56 |     dbForeignKey(const dbfield& local, const QString& parentTable, const QString& parentField, ODOU_Action delAction =NO_ACTION, ODOU_Action updAction =NO_ACTION)
>
>       |     ^~~~~~~~~~~~
>
> ../DKV2/dbfield.h:56:5: note:   candidate expects 5 arguments, 0 provided
>
> ../DKV2/dbfield.h:47:5: note: candidate: 'dbForeignKey::dbForeignKey(const dbfield&, const dbfield&, ODOU_Action, ODOU_Action)'
>
>    47 |     dbForeignKey(const dbfield& local, const dbfield& parent, ODOU_Action delAction =NO_ACTION, ODOU_Action updAction =NO_ACTION)
>
>       |     ^~~~~~~~~~~~
>
> ../DKV2/dbfield.h:47:5: note:   candidate expects 4 arguments, 0 provided
>
> ../DKV2/dbfield.h:43:8: note: candidate: 'dbForeignKey::dbForeignKey(const dbForeignKey&)'
>
>    43 | struct dbForeignKey
>
>       |        ^~~~~~~~~~~~
>
> ../DKV2/dbfield.h:43:8: note:   candidate expects 1 argument, 0 provided
>
> ../DKV2/dbfield.h:43:8: note: candidate: 'dbForeignKey::dbForeignKey(dbForeignKey&&)'
>
> ../DKV2/dbfield.h:43:8: note:   candidate expects 1 argument, 0 provided
>
>
>
> [....]
>
>
>
> make: *** [Makefile:851: dbtable.o] Error 1
>
> make: *** Waiting for unfinished jobs....
>
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Schachigel/DKV2/pull/85
> Commit Summary
>
>    - c7f72d5
>    <https://github.com/Schachigel/DKV2/pull/85/commits/c7f72d525c290760626b2a38a20b61c606d88660>
>    fix problems encountered while building
>    - 395b397
>    <https://github.com/Schachigel/DKV2/pull/85/commits/395b397d70645f51a84726fff74b6cb69395a9b7>
>    another location for qmake - because it is installed from the repo
>    - 517f01c
>    <https://github.com/Schachigel/DKV2/pull/85/commits/517f01cd73d3ba0edf9b98c3238de54cb2dbbb9d>
>    fix docker package name
>    - 190efa2
>    <https://github.com/Schachigel/DKV2/pull/85/commits/190efa2c880a59598801a56536a25a57ecfbf11a>
>    add tz-info to fix apt in docker
>    - b809acc
>    <https://github.com/Schachigel/DKV2/pull/85/commits/b809acc09d44ffb5d68e90d58ccf7d87648852b9>
>    remove aqtinstall and python dependencies
>    - 4ceb064
>    <https://github.com/Schachigel/DKV2/pull/85/commits/4ceb06465fd1c9203b83d67a0008aea886232b9a>
>    add qt from repository
>    - 7ed6841
>    <https://github.com/Schachigel/DKV2/pull/85/commits/7ed68410df8ae0b4a3b0ce176cec4024d250e6b3>
>    this helps to overcome a weird bug.
>
> File Changes
>
> (6 files <https://github.com/Schachigel/DKV2/pull/85/files>)
>
>    - *M* DKV2/contracttablemodel.cpp
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-d9676b2f2f40bc0db7110d2c260fea7bc262d0c8cd9a68ce7f20979ecfd71ee0>
>    (8)
>    - *M* DKV2/csvwriter.cpp
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-b2f610b375f7a78ccf50923343dc41dd10b1163f05b52da0cd372c7d6c345a00>
>    (1)
>    - *M* DKV2/mainwindow.cpp
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-258f1983b3bd90abc833b582e571f9279f8e9264843d8ee00e4c42d011a8429e>
>    (1)
>    - *M* DKV2/mainwindow.h
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-edbfe80532ab6586b16aee67554a8593d877c94f1a352c991be323f37c2d1080>
>    (1)
>    - *M* Dockerfile
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557>
>    (23)
>    - *M* dist_linux.sh
>    <https://github.com/Schachigel/DKV2/pull/85/files#diff-a0f11523ca71d86fffd4905fb6f3b1a6d921cf27529ff968cb1380c934800766>
>    (2)
>
> Patch Links:
>
>    - https://github.com/Schachigel/DKV2/pull/85.patch
>    - https://github.com/Schachigel/DKV2/pull/85.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Schachigel/DKV2/pull/85>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMYITUMQCG6U4Y6KKLYICM3WI2V4ZANCNFSM6AAAAAASD3WFWY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-11-20 08:03 UTC, Schachigel requested changes
der PR bricht die Github Action (Linux build) und läuft auch auf windows nicht. Brauchst Du wirklich einen docker build? Zu den Änderungen kann ich nichts sagen.
Vlt solltest Du schauen, ob Änderungen an Deinem System gemacht werden können  / müssen, um das zum laufen zu bekommen. Im Repo sollte immer eine "allgemeinere Lösung" der Speziellen von Deinem System vorgezogen werden.

2022-11-20 08:05 UTC, Schachigel commented on DKV2/csvwriter.cpp
> +#include <memory>
Auch in dieser Datei gibt es keine Verwendung. Ist Dein C++ up to date? Verwendest Du C++ 17?

2022-11-22 16:48 UTC, codders commented on Dockerfile
> +FROM ubuntu:20.04
Ich kann das bestätigen - `ubuntu-20.04` hier ist Falsch und `ubuntu:20.04` richtig

2022-11-23 14:32 UTC, plant-hedgerows commented
Hi holger,

ähm es tut mir leid, dass mein pull request nicht so funktioniert. Nachdem ich mir die ganze arbeit gemacht habe habe ich festgetellt, dass es einfach an der ubuntu version lag die hier verwendet wurde. 

Das neueste appimage lief nicht auf ubuntu 16.04.
Ich hab jetzt ein upgrade (auf 18.04) gemacht und jetzt geht es gut.

Tja.. Also ich habe mich mit dem build prozess deshalb beschäftigt, weil das im readme so steht. 

Dann ging es nicht - dann habe ich mich etwas eingehender mit dem dockerfile auseinandergesetzt und dachte ich will dir das nicht vorenthalten. 

Ich hab dann alles nur auf die ausführbarkeit des shell scriptes (docker build, docker run) hin optimiert.

Du hast recht, das es nicht die feine art ist am code rumzupfuschen, nur weil das dockerimage nicht geht. 

Den pfad im build script werd ich versuchen mit ins dockerfile zu tun. 

Ich hatte ein paar fehlermeldungen wegen irgendwelcher pointer und die gehen weg, wenn ich memory include - ich hab keine Ahnung von c, aber einen guten draht zu stackoverflow. Wahrscheinlich waren es dementsprechend keine guten Lösungen.

Ich würd gern mal telefonieren - auch was andere software projekte im mhs betrifft. Meine telefonnummer ist 017634673087

Viele liebe grüße, lukas
-- 
Gesendet mit pEp für Android.

2022-11-23 21:14 UTC, plant-hedgerows commented
Ich habe alle anderen Dateien die ich geändert habe rausgenommen. 
Ich hoffe dir @Frando gefällt die neue Dockerfile. Ubuntu 20.04 installiert per default qt 5.12.8 vielleicht liegt es daran, dass Fehler geworfen werden?

Jedenfalls funktioniert der Docker container so. 
Liebe Grüße!

2022-11-23 22:21 UTC, Schachigel approved these changes

2022-11-23 22:26 UTC, Schachigel commented
Alles klar, hab den PR so übernommen.

*>Tja.. Also ich habe mich mit dem build prozess deshalb beschäftigt, weil
das im readme so steht.*
Welches Readme meinst Du damit?

> *...telefonieren ...*
telco über BBB am Freitag Abend (halb 9)? Schreib mir doch mal über die
E-Mail Adresse, statt über GH

Gruß
Holger

Am Mi., 23. Nov. 2022 um 22:14 Uhr schrieb plant-hedgerows <
***@***.***>:

> Ich habe alle anderen Dateien die ich geändert habe rausgenommen.
> Ich hoffe dir @Frando <https://github.com/Frando> gefällt die neue
> Dockerfile. Ubuntu 20.04 installiert per default qt 5.12.8 vielleicht liegt
> es daran, dass Fehler geworfen werden?
>
> Jedenfalls funktioniert der Docker container so.
> Liebe Grüße!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Schachigel/DKV2/pull/85#issuecomment-1325663737>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMYITUMTVIVYF2DB46RIHV3WJ2CMZANCNFSM6AAAAAASD3WFWY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-23 22:40 UTC, merged

2022-11-23 23:00 UTC, plant-hedgerows commented
> Welches Readme meinst Du damit? 
ich meine BUILD.md -- vielleicht könnte man da etwas zu schreiben, es funktioniert ja nu immer noch nicht wirklich -- leider. 

> telco über BBB am Freitag Abend (halb 9)? Schreib mir doch mal über die E-Mail Adresse, statt über GH

ist okay - beides ich schreib dir nochmal.

2022-11-25 19:36 UTC, Schachigel commented
Meldest du dich noch?

plant-hedgerows ***@***.***> schrieb am Do. 24. Nov. 2022 um
00:00:

> Welches Readme meinst Du damit?
> ich meine BUILD.md -- vielleicht könnte man da etwas zu schreiben, es
> funktioniert ja nu immer noch nicht wirklich -- leider.
>
> telco über BBB am Freitag Abend (halb 9)? Schreib mir doch mal über die
> E-Mail Adresse, statt über GH
>
> ist okay - beides ich schreib dir nochmal.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Schachigel/DKV2/pull/85#issuecomment-1325747944>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMYITUIVJ2MJUIF2I7GPSG3WJ2OYNANCNFSM6AAAAAASD3WFWY>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>